In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold

In [46]:
# Import the dataset
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, 2:31].values
Y = dataset.iloc[:, 1].values
print(X)

[[ 17.99    10.38   122.8    ...   0.7119   0.2654   0.4601]
 [ 20.57    17.77   132.9    ...   0.2416   0.186    0.275 ]
 [ 19.69    21.25   130.     ...   0.4504   0.243    0.3613]
 ...
 [ 16.6     28.08   108.3    ...   0.3403   0.1418   0.2218]
 [ 20.6     29.33   140.1    ...   0.9387   0.265    0.4087]
 [  7.76    24.54    47.92   ...   0.       0.       0.2871]]


In [47]:
dataset.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [48]:
print('Dimensions: {}'.format(dataset.shape))

Dimensions: (569, 33)


In [49]:
# Finding missing or null data points
dataset.isnull().sum()
dataset.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [0]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [75]:
# Using 5-fold validation
accuracies = []

kfold = KFold(5, True, 1)
for train_idx, test_idx in kfold.split(X):
  x_train, x_test = X[train_idx], X[test_idx]
  y_train, y_test = Y[train_idx], Y[test_idx]

  # Feature scaling
  scaler = StandardScaler()
  x_train = scaler.fit_transform(x_train)
  x_test = scaler.transform(x_test)

  classifier = LogisticRegression(random_state=0)
  classifier.fit(x_train, y_train)
  y_pred = classifier.predict(x_test)
  cm = confusion_matrix(y_test, y_pred)

  total = sum(sum(cm))
  correct = cm[0][0] + cm[1][1]
  accuracy = (correct/total) * 100
  print("Logistic Regression Accuracy: {}%".format(accuracy))

  accuracies.append(accuracy)

Logistic Regression Accuracy: 98.24561403508771%
Logistic Regression Accuracy: 94.73684210526315%
Logistic Regression Accuracy: 96.49122807017544%
Logistic Regression Accuracy: 100.0%
Logistic Regression Accuracy: 96.46017699115043%


In [81]:
print('Average Logistic Regression Accuracy {}%'.format(sum(accuracies)/5))

Average Logistic Regression Accuracy 97.18677224033534%
